version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./splitwise-backend
      dockerfile: Dockerfile
      target: development
    container_name: splitwise-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/splitwise-dev?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      BCRYPT_ROUNDS: 12
    ports:
      - '3000:3000'
    volumes:
      - ./splitwise-backend:/app
      - /app/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - splitwise-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Application
  frontend:
    build:
      context: ./splitwise-ui
      dockerfile: Dockerfile
      target: production
    container_name: splitwise-frontend
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - splitwise-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3

  # Development Frontend (for hot reload)
  frontend-dev:
    build:
      context: ./splitwise-ui
      dockerfile: Dockerfile.dev
    container_name: splitwise-frontend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
    ports:
      - '4200:4200'
    volumes:
      - ./splitwise-ui:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - splitwise-network
    profiles:
      - dev

volumes:
  mongodb_data:
    driver: local

networks:
  splitwise-network:
    driver: bridge
